version: '3.8'

services:
  angular:
    hostname: angular,
    container_name: angular
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: sh -c "npm start"
    ports:
      - "4200:4200"
    depends_on:
      - nestjs
  nestjs:
    hostname: nestjs
    container_name: nestjs
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:8.0.28
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./server/.env
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: {}